### ISSUE TITLE
Differences between expected and obtained 1acj.bcif.gz when switching to OpenJDK17

### ISSUE THREAD

**Issue by pgrt** [rcsb/ciftools-java#12]
Hello,

I am one of the Debian maintainers of ciftools-java. Recently Debian switched from OpenJDK11 to OpenJDK17 and this caused a failure in WriterTest.writeBinary ([full Debian log](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1012093;filename=ciftools-java_3.0.1-1;msg=5)). I got the error with version 3.0.1 but also with version 4.0.3.

I could dig a bit more and compared the bytes of the expected and obtained Strings outputted in the log. Here are the first four lines of the xxd output:

$ xxd expected | head -n4
00000000: 1fef bfbd 0800 0000 0000 0000 efbf bd5d  ...............]
00000010: 0760 53ef bfbd efbf bd3f efbf bdef bfbd  .\`S......?......
00000020: 0eef bfbd 1214 0aef bfbd 7353 6959 efbf  ..........sSiY..
00000030: bd40 43ef bfbd 0eef bfbd 0eef bfbd efbf  .@C.............
$ xxd got | head -n4
00000000: 1fef bfbd 0800 0000 0000 00ef bfbd efbf  ................
00000010: bd5d 0760 53ef bfbd efbf bd3f efbf bdef  .].`S......?....
00000020: bfbd 0eef bfbd 1214 0aef bfbd 7353 6959  ............sSiY
00000030: efbf bd40 43ef bfbd 0eef bfbd 0eef bfbd  ...@C...........

As you can see, the diff is about removing 0000 in the expected string and adding 00ef bfbd instead.

I strongly suspect this is innocuous, as I met a similar issue with another project
https://github.com/broadinstitute/picard/issues/1840
and the authors explained the Java gzip implementation had changed, so that the change we see is normal. Do you also think so?

I would be happy to provide you with more details if needed. Thanks for your attention!

Best regards,

Pierre

**Comment by JonStargaryen** [comment]
Hi Pierre,

Thanks for the report. I also assume that this is harmless.
I've updated the test case to not pick up differences in the gzip implementation.

Version 4.0.4 should work again. I'll try to look into setting up a better toolchain that runs tests on Java 11 and 17 in the future.

Cheers,
Sebastian

**Comment by pgrt** [comment]
Hi Sebastian,

Thanks for your prompt answer, I highly appreciate it!

The reported issue is the only problem I noticed when switching to OpenJDK17, I trust you won't have much difficulties on your side either.

Cheers,
Pierre
