### ISSUE TITLE
classes and categories need to be loaded lazily (for SwingJS)

### ISSUE THREAD

**Issue by BobHanson** [rcsb/ciftools-java#5]
Latest update is appreciated, particularly for adding generic string-based references to CIF tags. The purpose of that generic option is to reduce the required download in SwingJS, however, and we still see a preliminary load for DemoReadGeneric of 789 classes (777 when I remove the StandardCharSets dependency of MessagePack), including 666 from rcsb, resulting in a download of 4.7 MB compressed:

12/05/2019  01:09 PM         4,742,217 core_cifdemo.z.js

The "generic"/properties idea is specifically designed to avoid that. My fork is requiring only 152 classes (just 41 from rcsb), bringing that to a much more respectable 0.8 MB:

12/05/2019  01:05 PM           790,585 core_cifdemo.z.js

This, of course, includes the full extent of the Java(Script) Runtime Environment that is required to load and run DemoReadGeneric. If we check how much the rcsb code contributes, we are down to just 96K for the rcsb classes:

12/05/2019  01:51 PM            95,657 core_cifdemo.z.js
 
To me, that sounds pretty reasonable for a binaryCIF reader. 

I am fairly certain that this efficiency requires use of Properties for two reasons:

First, for generic loading, the problem is a relatively simple one: Make sure ModelFactory only creates CATEGORY_MAP and COLUMN_MAP if needed -- which is when generic loading not used or when text-CIF is being read (generic or not).

Second, for nongeneric loading, we still do not need to load all 600+ categories and map all 7000+ columns. That is the huge download hit, because it requires loading all those categories (as well as the 350K field-name-class-map.csv file).

The solution thus requires both something like a set of property files (compacted to 130K in my implementation, but deliverable in mostly tiny 1-3 KB sets) as well as reflection in order to avoid the downloading of all the category files when text generic or non-generic reading is done. 

Also, just to note, even with that, my code is executing at two to five times the speed of rcsb/ciftools in JavaScript reading 3j9m, even when I add the raw column business to ciftools that I propose to speed all column data access. So there is still something there that is an issue. 

My reference implementation is at 
https://github.com/BobHanson/ciftools-java
with JavaScript site as 
https://github.com/BobHanson/ciftools-java/blob/swingjs/dist/ciftools_site.zip?raw=true

I note that with Chrome, now, for 3j9m, I am seeing the following report from DemoReadGeneric in JavaScript:

rcsb/ciftools-java, with additions for rapid column data retrieval:

5    niter=11    processStream BINARY StreamParser
5    niter=11    processStream BINARY StreamParser
5    niter=11    processStream BINARY StreamParser
5    niter=11    processStream BINARY StreamParser
140    niter=10    ------PARSE binary (-GC)
140    niter=10    ------PARSE binary

bobhanson/ciftools-java, with the same:

1    niter=11    processStream BINARY StreamParser
1    niter=11    processStream BINARY StreamParser
1    niter=11    processStream BINARY StreamParser
1    niter=11    processStream BINARY StreamParser
85    niter=10    ------PARSE binary (-GC)
85    niter=10    ------PARSE binary
Demo complete

compared to Java:

0	niter=11	processStream BINARY StreamParser
0	niter=11	processStream BINARY StreamParser
1	niter=11	processStream BINARY StreamParser
1	niter=11	processStream BINARY StreamParser
14	niter=10	------PARSE binary (-GC)
29	niter=10	------PARSE binary

(where -GC is removing garbage collection from the time for Java)

The 11-iteration time is an average for decoding the cartn_[x,y,z] columns of atom_site and averaging cartn_x. 
The 10-iteration time is an average that includes parsing building the CifFile object. 

I do appreciate that even 140 ms for building a CifFile object -- reading 3j3m in its entirety -- is a huge win for binaryCIF! I'm just being greedy here.

**Comment by JonStargaryen** [comment]
Addressed in version 0.7.0.
