### ISSUE TITLE
unsigned int messagepack methods does not return an unsigned int

### ISSUE THREAD

**Issue by BobHanson** [rcsb/ciftools-java#6]
The following method should return a long, not an int. 

    private int readUnsignedInt(DataInputStream inputStream) throws IOException {
        return (int) (inputStream.readInt() & 0xFFFFFFFFL);
    }

As written, this just returns a number in the normal int range [Integer.MIN_VALUE, Integer.MAX_VALUE]. Larger numbers must be cast as long, not int.

**Comment by JonStargaryen** [comment]
Yeah, it's pretty much meaningless. The returned value is (exclusively?) used as index during array access.  In that context, `long` won't compile and `0xFFFFFFFFL` acts as safety net for negative values.

The encoder will serialize large, positive `int` values as uint32:
https://github.com/rcsb/ciftools-java/blob/875021a02ee430e33334868ef67c08c2b680d84d/src/main/java/org/rcsb/cif/binary/codec/MessagePackCodec.java#L112 
However, these values are really just normal, signed int with 32 bit which happen to be represented using the `uint32` type tag of MessagePack. We know that the BinaryCIF codec implementations around (Java & JavaScript/TypeScript) will only write values with the `uint32` tag which can correctly represented as `int`.

Maybe it should just delegate to `DataInputStream#readInt()`. Anything negative or larger than `Integer.MAX_VALUE` causes undefined behavior. Maybe the current approach is not the best way to handle this.
