### ISSUE TITLE
Provide command line interface to test parsing of any CIF

### ISSUE THREAD

**Issue by merkys** [rcsb/ciftools-java#9]
Currently, `Demo.java` has a nice command line interface to test parsing of `1acj` PDB entry:
https://github.com/rcsb/ciftools-java/blob/c589bd5a66b5a86341fe03b08739d9e8b4d443e3/src/main/java/org/rcsb/cif/Demo.java#L17-L23
It would be great if `main` in `Demo.java` could accept a filename to parse, and fallback on `1acj` if not given anything.

I am doing a [comparison of CIF readers](https://github.com/cod-developers/CIF-parsers) and would like to include CIFTools (https://github.com/cod-developers/CIF-parsers/issues/4). To do so I need a command line interface to parse a given file. I believe having such command line interface would benefit other purposes as well, for example, to see if a CIF file parses correctly.

**Comment by JonStargaryen** [comment]
Hi @merkys,

That's nice to hear. I've ran some of your test cases and this implementation looks quite forgiving when it comes to malformed files.

Something along these lines should allow you to test files via the command-line:
```java
import java.nio.file.Paths;

public class Validate {
    public static void main(String[] args) {
        try {
            CifIO.readFromPath(Paths.get(args[0]));
        } catch (Exception e) {
            System.out.println("Not OK: " + e.getClass().getSimpleName() + " - " + e.getMessage());
        }
    }
}
```

Let me know if you'd like me to compile this into a runnable `.jar` and send it to you. I would rather not commit any changes related to this issue to the repo.

Best,
Sebastian
